[unstable]
build-std-features = ["compiler-builtins-mem"]  # 启用编译器内建内存支持
build-std = ["core", "compiler_builtins"]  # 构建核心库和编译器内建库
[build]
target = "aarch64-blog_os.json"

[dependencies]
bootloader = "0.9"  # 引导程序依赖

[target.aarch64-blog_os]
linker = "/opt/homebrew/bin/lld"